import { AboutSlint, Button } from "std-widgets.slint";

export global AboutMetadata {
    in property <string> version;
}

export component About {
    width: 260px;
    height: 260px;
    VerticalLayout {
        alignment: LayoutAlignment.center;
        padding: 16px;
        spacing: 8px;
        VerticalLayout {
            spacing: 2px;
            Text {
                font-size: 20px;
                horizontal-alignment: TextHorizontalAlignment.center;
                text: "Slinter v\{AboutMetadata.version}";
            }
            Text {
                font-italic: true;
                font-size: 14px;
                horizontal-alignment: TextHorizontalAlignment.center;
                text: "made by @realkinja";
            }
        }

        AboutSlint {
            height: 180px;
            x: (parent.width - self.width) / 2;
        }
    }
}