import { Button, VerticalBox, TabWidget, ScrollView, GroupBox } from "std-widgets.slint";
import { About, AboutMetadata } from "./about.slint";
import { UpgradesTab, UpgradesLogic } from "./upgrades.slint";
export { UpgradesLogic, AboutMetadata }

export component Window inherits Window {
    title: "Slinter";
    icon: @image-url("../images/icon.png");

    min-width: 480px;
    min-height: 480px;
    in property <int> clicks: 0;
    in property <int> cps_counter: 0;
    in property <int> current_cps: 0;
    in property <int> upgradecps: 0;

    callback request-increase-value();

    TabWidget {
        Tab {
            title: "Clicker";
            VerticalLayout {
                alignment: LayoutAlignment.center;
                padding: 16px;
                spacing: 4px;
                VerticalBox {
                    spacing: 0px;
                    alignment: LayoutAlignment.center;
                    Text {
                        font-size: 16px;
                        text: "Clicks: \{root.clicks}";
                    }
        
                    Text {
                        font-size: 16px;
                        text: "CPS: \{root.current_cps}";
                    }
        
                    Text {
                        font-size: 16px;
                        text: "Upgrades' CPS: \{root.upgradecps}";
                    }
                }
        
                VerticalLayout {
                    clickbutton := Button {
                        height: 40px;
                        primary: true;
                        text: "Clickity click";
                        clicked => {
                            root.request-increase-value();
                            clickbutton.clear-focus();
                        }
                    }
                }
            }  
        }
        Tab {
            title: "Upgrades";
                ScrollView {
                    width: 100%;
                    height: 100%;
                    viewport-height: root.height;
                    VerticalLayout {
                        UpgradesTab {}
                    }
                }
        }

        Tab {
            title: "About";
            About { }
        }
    }
} 